version: '3'

services:
  ui:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:10.15-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/opt/ui
    working_dir: /opt/ui

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/server/
    command: uvicorn app.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
    depends_on:
      - database
  
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d