"""add jobs table

Revision ID: 5b1f22e1b384
Revises: 
Create Date: 2023-11-11 14:25:10.067850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b1f22e1b384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_category', table_name='jobs')
    op.drop_index('idx_jobs_suburb', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_suburbs_postcode', table_name='suburbs')
    op.drop_table('suburbs')
    op.drop_index('idx_categories_parent_category', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('parent_category_id', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_categories_parent_category', 'categories', ['parent_category_id'], unique=False)
    op.create_table('suburbs',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('postcode', mysql.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_suburbs_postcode', 'suburbs', ['postcode'], unique=False)
    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'new'"), nullable=False),
    sa.Column('suburb_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('contact_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_phone', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_jobs_category'),
    sa.ForeignKeyConstraint(['suburb_id'], ['suburbs.id'], name='fk_jobs_suburb'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_jobs_suburb', 'jobs', ['suburb_id'], unique=False)
    op.create_index('idx_jobs_category', 'jobs', ['category_id'], unique=False)
    # ### end Alembic commands ###
